apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec:
      serviceAccount: server
      containers:
        - name: goserver
          image: luks3110/hello-go:v5.3

          resources:
            requests:
              cpu: "0.05"
              memory: "20Mi"
            limits:
              cpu: "0.05"
              memory: "128Mi"

          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 3

          envFrom:
            - configMapRef:
                name: "goserver-env"
            - secretRef:
                name: "goserver-secret"

          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
            - mountPath: "/go/pvc"
              name: goserver-pvc

      volumes:
        - name: goserver-pvc
          persistentVolumeClaim:
            claimName: goserver-pvc

        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt
